### ISSUE TITLE
Can't get bomb state?

### ISSUE THREAD

**Issue by Colcothar** [Erlendeikeland/csgo-gsi-python#1]
"{'player': None, 'position': None, 'state': None, 'countdown': None}"

Bomb state reports as the above. Doesn't change regardless of being planted defused etc. Any ideas?

**Comment by tricyphona** [comment]
Has this ever worked for you, if not since when do you use it? 
Are you observing the game (not playing)?
I assume other info is displaying correctly?
In your gamestate.cfg file, is there under data:"bomb"		"1"

When I am spectating a bot game on Dust II the bomb state updates correctly. (using cs:go with buildID 5640798)

**Comment by Colcothar** [comment]
I've never been able to get this to work. Definitely playing the game, I get all other stats displayed correctly.
Bomb is set to 1 in cfg.

As an experiment, I've set the payload to print. Everything shows, I can provide a copy if you're interested, but theres no reference to "bomb".

Thanks for helping me out and checking that for me - It is appreciated.

**Comment by tricyphona** [comment]
[github_gamestatecopy.txt](https://github.com/Erlendeikeland/csgo-gsi-python/files/5361081/github_gamestatecopy.txt)
I've attached my gamestate file.
In payloadparser.py, can you add:"
            if item == 'bomb':
                print(payload[item])
" after "for item in payload:"?
When a player is planting (while spectating) I get: {'state': 'planting', 'position': '1057.1, 2602.3, 96.0', 'countdown': '0.612', 'player': 76561197960265733}
Some stats only show while spectating (cause of unfair advantage)

**Comment by Colcothar** [comment]
Got it, thanks very much.

I had seen some other integrations make use of getting bomb state whilst playing as T or CT (to set keyboard LED colour) - so assumed it was possible

**Comment by tricyphona** [comment]
Yes, you can determine the state of the bomb! 
When you read 'round', it'll show the state of the bomb as soon as it is planted. You can determine a countdown of the bomb (since you know when it was planted). But the information obtained is a lot more limited. 
Hope this helps!

**Comment by Colcothar** [comment]
All makes sense now! 

Thanks for your help!
